<div class="header-top-desktop">
	<?php
	echo $block->getLayout()

	->createBlock('Magento\Cms\Block\Block')

	->setBlockId('header-top-left')

	->toHtml();

	?>
</div>
<div class="header-top-desktop">	
	<?php
	echo $block->getLayout()

	->createBlock('Magento\Cms\Block\Block')

	->setBlockId('header-top-center')

	->toHtml();

	?>
</div>

<div class="header-top-mobile">	
	<?php
	echo $block->getLayout()

	->createBlock('Magento\Cms\Block\Block')

	->setBlockId('header-mobile-address')

	->toHtml();

	?>
</div>

<div class="header-top-mobile">
	<?php
	echo $block->getLayout()

	->createBlock('Magento\Cms\Block\Block')

	->setBlockId('header-mobile-phone')

	->toHtml();

	?>
</div>

