<div class="bestseller">
    <?php
        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bestseller-demo')->toHtml();
    ?>
</div>

<script>
    require(['jquery', 'slick'], function($) {
	    $(document).ready(function() {
	        $(".product-items").slick({
	            infinite: true,
	            slidesToShow: 5,
                slidesToScroll: 5,
                arrows: false,
                swipeToSlide: true,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 3,
                            infinite: true,
                        }
                    },
                    {
                        breakpoint: 600,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 330,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }
                ]
	        });
	    });
	});
</script>