<div class="category-banner-title">
    <?php 
        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category-banner-title')->toHtml();
    ?>

    <div class="category-banner-title-content">
        <?php 
            echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category-banner-title-content')->toHtml();
        ?>
    </div>
</div>